service: kar-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler
  s: handler.hello
    events:
      - httpApi:
          path: /
          method: get
